kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:
      containers:
        - name: nginx
          image: darshanm416/nginx:1.0.1
          ports: 
            - containerPort: 80